--require "dirtree"

library_path = get_library_path()

file = io.open(library_path.."/LibraryStructure.txt", "w+")

file:write("-- This file is autogenerated.\n")
file:write("-- Don't keep any info here unless you want to lose it.\n\n")

file:write(library_path, '/', "\n")
for filename, attr in dirtree(library_path) do
  local relative = string.sub(filename, string.len(library_path) + 2, -1)
  if (attr.mode == "directory") then
    relative = relative.."/"
  end
  file:write(relative, "\n")
end
