--require "dirtree"

image_folder_path = get_library_path().."/images"

autoload = io.open(image_folder_path.."/Autoload.txt", "w+")
image_list = io.open(image_folder_path.."/ImageList.txt", "w+")

autoload:write("-- This file is autogenerated.\n")
autoload:write("-- Don't keep any info here unless you want to lose it.\n\n")

image_list:write("-- This file is autogenerated.\n")
image_list:write("-- Don't keep any info here unless you want to lose it.\n\n")
image_list:write("-- This file is here for the convenience of maintaining pictures.\n")
image_list:write("-- Set your cursor on any picture header and press <leader> + pe to expand it.\n")
image_list:write("-- Press <leader> + pa to expand all pictures.\n\n")

for filename, attr in dirtree(image_folder_path) do
  local relative = string.sub(filename, string.len(image_folder_path) + 2, -1)

  reverse = relative:reverse()
  dot = reverse:find(".", 1, true)
  local ext = ""
  if (dot ~= nil) then
      ext = reverse:sub(1, dot):reverse()
  end

  if (attr.mode ~= "directory" and (
        ext == ".png" or
        ext == ".bmp" or
        ext == ".jpg" or
        ext == ".dds" or
        ext == ".tga" or
        ext == ".psd" or
        ext == ".jpeg")) then
      autoload:write(relative, "\n")
      image_list:write("<|"..relative.."|10|0|>", "\n\n")
  end

end
